module OPNsenseAPI
  module Core
    class Diagnostics
      class Netflow
        include OPNsenseAPI::Core

        BASE_PATH: String

        def cache_stats: (?Hash[untyped, untyped] params) -> untyped

        def get_config: (?Hash[untyped, untyped] params) -> untyped

        def is_enabled: (?Hash[untyped, untyped] params) -> untyped

        def reconfigure: (?Hash[untyped, untyped] body) -> untyped

        def set_config: (?Hash[untyped, untyped] params) -> untyped

        def status: (?Hash[untyped, untyped] params) -> untyped
      end
    end
  end
end
