module OPNsenseAPI
  module Core
    class Diagnostics
      class NetworkInsight
        include OPNsenseAPI::Core

        BASE_PATH: String

        def get_interfaces: (?Hash[untyped, untyped] params) -> untyped

        def get_metadata: (?Hash[untyped, untyped] params) -> untyped

        def get_protocols: (?Hash[untyped, untyped] params) -> untyped

        def get_services: (?Hash[untyped, untyped] params) -> untyped
      end
    end
  end
end
