module OPNsenseAPI
  module Core
    class IPSec
      class Sessions
        include OPNsenseAPI::Core

        BASE_PATH: String

        def connect: (?Hash[untyped, untyped] body, id: String) -> untyped

        def disconnect: (?Hash[untyped, untyped] body, id: String) -> untyped

        def search_phase_1: (?Hash[untyped, untyped] params) -> untyped

        def search_phase_2: (?Hash[untyped, untyped] params) -> untyped
      end
    end
  end
end
