module OPNsenseAPI
  module Core
    class Routes
      class Gateway
        include OPNsenseAPI::Core

        BASE_PATH: String

        def status: (?Hash[untyped, untyped] params) -> untyped
      end
    end
  end
end
