module OPNsenseAPI
  module Core
    class Firewall
      class Alias
        include OPNsenseAPI::Core

        BASE_PATH: String

        def add_item: (?Hash[untyped, untyped] body) -> untyped

        def del_item: (uuid: String) -> untyped

        def export: (?Hash[untyped, untyped] params) -> untyped

        def get: (?Hash[untyped, untyped] params) -> untyped

        def get_alias_uuid: (name: untyped) -> untyped

        def get_geo_ip: (?Hash[untyped, untyped] params) -> untyped

        def get_item: (uuid: String) -> untyped

        def get_table_size: (?Hash[untyped, untyped] params) -> untyped

        def import: (?Hash[untyped, untyped] body) -> untyped

        def list_categories: (?Hash[untyped, untyped] params) -> untyped

        def list_countries: (?Hash[untyped, untyped] params) -> untyped

        def list_network_aliases: (?Hash[untyped, untyped] params) -> untyped

        def reconfigure: (?Hash[untyped, untyped] body) -> untyped

        def search_item: (?Hash[untyped, untyped] body) -> untyped

        def set: (?Hash[untyped, untyped] body) -> untyped

        def set_item: (uuid: String, ?body: Hash[untyped, untyped]) -> untyped

        def toggle_item: (uuid: String, ?enabled: bool?) -> untyped
      end
    end
  end
end
