module OPNsenseAPI
  module Core
    class Firewall
      class FilterUtil
        include OPNsenseAPI::Core

        BASE_PATH: String

        def rule_stats: (?Hash[untyped, untyped] params) -> untyped
      end
    end
  end
end
